version: "3"
services:
  app:
    tty: true
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - development.env
    networks:
      - sandbox-network
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file:
      - development.env
    networks:
      - sandbox-network

networks:
  sandbox-network: