version: "3"
services:
  app:
    container_name: sandbox_api
    tty: true
    entrypoint: /go/src/sandbox-api/startserver.sh
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/go/src/sandbox-api:cached
    depends_on:
      - db
      - redis
    env_file:
      - development.env
    networks:
      - sandbox-network
  db:
    container_name: sandbox_db
    build: ./db
    ports:
      - 3306:3306
    env_file:
      - development.env
    networks:
      - sandbox-network
  nginx:
    container_name: sandbox_proxy
    build: ./nginx
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - sandbox-network
  redis:
    container_name: sandbox_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - sandbox-network

networks:
  sandbox-network:
    external: true